export { default as FooterHero } from "./FooterHero"
export { default as FooterNewsletter } from "./FooterNewsletter"
export { default as FooterLinks } from "./FooterLinks"
export { default as FooterContact } from "./FooterContact"
export { default as FooterBottom } from "./FooterBottom" 