gallery:
  - img: /images/product-page-01.jpg
  - img: /images/product-page-02.jpg
  - img: /images/product-page-03.jpg
  - img: /images/product-page-04.jpg
  - img: /images/product-page-05.jpg
  - img: /images/product-page-06.jpg
  - img: /images/product-page-07.jpg
  - img: /images/product-page-08.jpg

products:
  - image: /images/product-16.jpg
    category: chair
    title: Bow Chair
    price: $1390.00
    label: none
  - image: /images/product-04.jpg
    category: table
    title: Piper Bar
    price: $1390.00
    label: hot
  - image: /images/product-06.jpg
    category: decor
    title: Golden Clock
    price: $1390.00
    label: none
  - image: /images/product-05.jpg
    category: Table
    title: Piper Bar
    price: $1390.00
    label: none
  - image: /images/product-16.jpg
    category: decor
    title: Golden Clock
    price: $1390.00
    label: none
  - image: /images/product-04.jpg
    category: Table
    title: Piper Bar
    price: $1390.00
    label: none
  - image: /images/product-26.jpg
    category: decor
    title: Golden Clock
    price: $1000.00
    sale: $1390.00
    label: sale
  - image: /images/product-05.jpg
    category: Table
    title: Piper Bar
    price: $1390.00
    label: hot
comments:
  - image: /images/tes_01.png
    date: Nov 20, 2020
    name: Dean. D
    content: It has a really nice fit however it loses many fluffs and is kind of see-through because the fabric is quite wid-meshed. Nevertheless it's a really good and comfy staple that goes with every kind.
  - image: /images/tes_02.png
    date: Nov 20, 2020
    name: Dean. D
    content: It has a really nice fit however it loses many fluffs and is kind of see-through because the fabric is quite wid-meshed. Nevertheless it's a really good and comfy staple that goes with every kind.
  - image: /images/tes_03.png
    date: Nov 20, 2020
    name: Dean. D
    content: It has a really nice fit however it loses many fluffs and is kind of see-through because the fabric is quite wid-meshed. Nevertheless it's a really good and comfy staple that goes with every kind.